// Generated by https://quicktype.io

import { ExperienceItem } from "./ExperienceItem.model";
import { FormationItem } from "./FormationItem.model";
import { LangueItem } from "./LangueItem.model";
import { LienItem } from "./LienItem.model";

export interface SectionPositionList {
    count: number;
    rows:  SectionPositionItem[];
    page:  number;
}

export interface SectionPositionItem {
    id:                         number;
    intitule:                   string;
    description:                string;
    type:                       string;
    position:                   Position;
    ordre:                      number;
    createdAt:                  string;
    updatedAt:                  string;
    deletedAt:                  null;
    CvId:                       number;
    Formations:                 FormationItem[];
    ExperienceProfessionnelles: ExperienceItem[];
    Liens:                      LienItem[];
    Langues:                    LangueItem[];
}



export enum Position {
    Gauche = "gauche",
    Droit = "droit"
}







