// Generated by https://quicktype.io

export interface TemplateItem {
    id:              number;
    intitule:        string;
    configParDefaut: string;
    image:           string;
    createdAt:       string;
    updatedAt:       string;
    deletedAt:       string;
}
