services:
   client:
      image: ghcr.io/ola-awaly/cvgenerator/cvgeneratorclient:latest

      pull_policy: always
      networks:
         - proxy_cvgenerator

   server:
      image: ghcr.io/ola-awaly/cvgenerator/cvgeneratorserver:latest
      environment:
       - HOST_DB=${HOST_DB}
       - USER_DB=${USER_DB}
       - NAME_DB=${NAME_DB}
       - PASSWORD_DB=${PASSWORD_DB}
       - PORT_DB=${PORT_DB}
       - CUR_HOST=${CUR_HOST}
       - MAIL_USERNAME=${MAIL_USERNAME}
       - OAUTH_CLIENTID=${OAUTH_CLIENTID}
       - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
       - OAUTH_REFRESH_TOKEN=${OAUTH_REFRESH_TOKEN}
       - JWTPRIVATEKEY=${JWTPRIVATEKEY}
       - JWTPUBLICKEY=${JWTPUBLICKEY}
      deploy:
         #  replicas: 3
         #  update_config:
         #     parallelism: 1
         #     delay: 10s
         restart_policy:
            condition: on-failure
      pull_policy: always
      restart: always
      networks:
         - proxy_cvgenerator
  
    db:
      image: mysql:8.0.39
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: cvgenerator
      volumes:
         - db_data:/var/lib/mysql
         - ./server/cvgenerator.sql:/docker-entrypoint-initdb.d/cvgenerator.sql
      ports:
         - '3307:3306'
      networks:
         - proxy_cvgenerator
   # reverse-proxy:
   #    image: ghcr.io/ola-awaly/mastermind/reverse-proxy:latest
   #    ports:
   #       - 80:80
   #    restart: unless-stopped
   #    depends_on:
   #       - mastermindserver
   #       - db
   #       - mastermindclient
volumes:
   mydb:
networks:
   proxy_mastermind:
      external: true
