services:
   db:
      image: mysql:8.0.39
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: cvgenerator
      volumes:
         - db_data:/var/lib/mysql
         - ./server/cvgenerator.sql:/docker-entrypoint-initdb.d/cvgenerator.sql
      ports:
         - '3307:3306'
      networks:
         - proxy_cvgenerator
   server:
      build:
         context: ./server
         dockerfile: Dockerfile.prod
      ports:
         - '8081:8080'
      env_file:
         - './server/.env'
      volumes:
         - type: bind
           source: ./server
           target: /server
         - type: volume
           target: /server/node_modules
      depends_on:
         - db
      restart: unless-stopped
      networks:
         - proxy_cvgenerator
   client:
      build:
         context: ./client
         dockerfile: Dockerfile.prod

      volumes:
         - ./client:/client:rw
         - type: volume
           target: /client/node_modules
      depends_on:
         - db
         - server
      networks:
         - proxy_cvgenerator

volumes:
   db_data:
networks:
   proxy_cvgenerator:
